### ISSUE TITLE
Not opening the page

### ISSUE THREAD

**Issue by srihari1234** [frumbert/moodle-course_meta#1]
Hi This is srihari. i try to install the plugin but it showed success but not redirecting the page,
It shows like this blank page.

http://localhost/TrainingDev/Trainingwww/admin/upgradesettings.php?

Here I want  to change anything.

**Comment by frumbert** [comment]
Well, firstly I can't see your computer. So you can't post links to "localhost" and hope any anyone but you can see them.

Next, you'll have to tell me about your environment. Start with what server environment you are running, and also what specific Moodle version.

i imagine you're seeing the blank page that means an error has occurred but you haven't turned on debugging. So you'll have to turn that on by modifying your config.php, as described [here](https://docs.moodle.org/28/en/Debugging).

Next, let me know what kind of php errors you are seeing. You'll have to use either the moodle debugging environment settings, or a copy of the tail of the php error log in order to find these out. Can you also confirm the set of permissions the sql user has, since it requires specific ones related to how it builds the database view.

Finally, you'll have to list down, in order, the steps you took and any messages you encountered along the way, particular during the stage where you installed the plugin.

Then I can help.

**Comment by srihari1234** [comment]
![Uploading blank page.png…]()

**Comment by srihari1234** [comment]
I am working on wamp server.And the moodle version is 2.1.
It is for online training and online examination.
It is not shown any error when installing the plugin but i did not change any settings.
And just i copied that two folders to my local directory.

**Comment by frumbert** [comment]
OK, but without you taking any of the steps I listed, i can't help you. Moodle 2.1 is pretty old - it came out in December 2011. Is there a reason you aren't using a later version?

**Comment by srihari1234** [comment]
Yes,Its already running website in corporate company.So i am working on that.
