### ISSUE TITLE
Not opening the page

### ISSUE THREAD

**Issue by srihari1234** [frumbert/moodle-course_meta#2]
Yes,Its already running website in corporate company.So i am working on that.

**Comment by frumbert** [comment]
In order to garner support for this plugin, you'll need to:
1. Post your issue in the correct place. The [Moodle Tracker](https://tracker.moodle.org/browse/MDL-34634) isn't the support forum for this plugin, or in fact related to it.
2. Don't open new jobs for existing problems. Re-open existing tickets. Learn to use the tools you have.
3. Tell me the exact versions of Moodle that you have.
4. Tell me about your server. Is it apache2? Is it IIS7.5 with fast-cgi?
5. Tell me which branch of this plugin you downloaded. 
6. Tell me the exact steps you took to install the plugin, including any changes to your config.php that you took.
7. Tell me the exact steps you took in activating the plugin within moodle.
8. Enable your moodle php developer debugging set to extra messages level.
9. When the error is encountered, tail the php error log and attach it to the ticket.
10. Post either the exact error you are encountering or a screenshot of the error.

If you can't supply all of these details, your problem can't be supported.

Closing **this** job since _it's not a question_.
